openapi: 3.0.0
info:
  title: Coral Finance API
  version: 1.0.0
  description: Documentación de la API de Coral Finance
servers:
  - url: http://localhost:3000
    description: Servidor local (modo desarrollo)
  - url: http://localhost:5000
    description: Servidor local alternativo / entorno de pruebas
paths: {}
