export interface OccupationOption {
  value: string;
  label: string;
  text: string;
}

export const OCCUPATIONS: OccupationOption[] = [
  { value: "11-1011", label: "Chief Executives", text: "Directores Ejecutivos" },
  { value: "11-1031", label: "Legislators", text: "Legisladores" },
  { value: "11-2011", label: "Advertising and Promotions Managers", text: "Directores de Publicidad y Promoción" },
  { value: "11-2031", label: "Public Relations and Fundraising Managers", text: "Directores de Relaciones Públicas y Recaudación de Fondos" },
  { value: "11-3031", label: "Financial Managers", text: "Directores Financieros" },
  { value: "11-3051", label: "Industrial Production Managers", text: "Directores de Producción Industrial" },
  { value: "11-3071", label: "Transportation, Storage, and Distribution Managers", text: "Directores de Transporte, Almacenamiento y Distribución" },
  { value: "11-9021", label: "Construction Managers", text: "Directores de Construcción" },
  { value: "11-9041", label: "Architectural and Engineering Managers", text: "Directores de Arquitectura e Ingeniería" },
  { value: "11-9071", label: "Gaming Managers", text: "Directores de Juego" },
  { value: "11-9141", label: "Property, Real Estate, and Community Association Managers", text: "Directores de Propiedad, Inmobiliaria y Asociaciones Comunitarias" },
  { value: "13-1011", label: "Agents and Business Managers of Artists, Performers", text: "Agentes y Directores de Artistas y Actores" },
  { value: "13-1041", label: "Compliance Officers", text: "Oficiales de Cumplimiento" },
  { value: "13-1131", label: "Fundraisers", text: "Recaudadores de Fondos" },
  { value: "13-2011", label: "Accountants and Auditors", text: "Contadores y Auditores" },
  { value: "13-2021", label: "Appraisers and Assessors of Real Estate", text: "Peritos y Tasadores de Propiedad Inmobiliaria" },
  { value: "13-2051", label: "Financial Analysts", text: "Analistas Financieros" },
  { value: "13-2052", label: "Personal Financial Advisors", text: "Asesores Financieros Personales" },
  { value: "13-2053", label: "Insurance Underwriters", text: "Subastadores de Seguros" },
  { value: "13-2061", label: "Financial Examiners", text: "Examinadores Financieros" },
  { value: "13-2081", label: "Tax Examiners and Collectors, and Revenue Agents", text: "Examinadores y Recaudadores de Impuestos, y Agentes de Ingresos" },
  { value: "13-2082", label: "Tax Preparers", text: "Preparadores de Impuestos" },
  { value: "13-2099", label: "Financial Specialists, All Other", text: "Especialistas Financieros, Todos los Otros" },
  { value: "17-2051", label: "Civil Engineers", text: "Ingenieros Civiles" },
  { value: "17-2151", label: "Mining and Geological Engineers, Including Mining Safety", text: "Ingenieros de Minería y Geológicos, Incluyendo Seguridad Minera" },
  { value: "17-2161", label: "Nuclear Engineers", text: "Ingenieros Nucleares" },
  { value: "17-2171", label: "Petroleum Engineers", text: "Ingenieros de Petróleo" },
  { value: "17-2199", label: "Engineers, All Other", text: "Ingenieros, Todos los Otros" },
  { value: "19-1041", label: "Epidemiologists", text: "Epidemiólogos" },
  { value: "19-2042", label: "Geoscientists, Except Hydrologists and Geographers", text: "Geocientíficos, Excepto Hidrologistas y Geógrafos" },
  { value: "19-3011", label: "Economists", text: "Economistas" },
  { value: "19-4041", label: "Geological and Petroleum Technicians", text: "Técnicos de Geología y Petróleo" },
  { value: "19-4051", label: "Nuclear Technicians", text: "Técnicos Nucleares" },
  { value: "23-1011", label: "Lawyers", text: "Abogados" },
  { value: "23-1021", label: "Administrative Law Judges, Adjudicators, and Hearing Officers", text: "Jueces de Derecho Administrativo, Árbitros y Oficiales de Audiencia" },
  { value: "23-1023", label: "Judges, Magistrate Judges, and Magistrates", text: "Jueces, Jueces Magistrados y Magistrados" },
  { value: "25-4012", label: "Curators", text: "Curadores" },
  { value: "27-1011", label: "Art Directors", text: "Directores de Arte" },
  { value: "27-1012", label: "Craft Artists", text: "Artistas Artesanos" },
  { value: "27-1013", label: "Fine Artists, Including Painters, Sculptors, and Illustrators", text: "Artistas Fine, Incluyendo Pintores, Escultores e Ilustradores" },
  { value: "27-1019", label: "Artists and Related Workers, All Other", text: "Artistas y Trabajadores Relacionados, Todos los Otros" },
  { value: "27-1021", label: "Commercial and Industrial Designers", text: "Diseñadores Comerciales e Industriales" },
  { value: "27-2012", label: "Producers and Directors", text: "Productores y Directores" },
  { value: "27-2021", label: "Athletes and Sports Competitors", text: "Atletas y Competidores Deportivos" },
  { value: "27-2022", label: "Coaches and Scouts", text: "Entrenadores y Scouts Deportivos" },
  { value: "27-2023", label: "Umpires, Referees, and Other Sports Officials", text: "Árbitros, Árbitros Deportivos y Otros Oficiales Deportivos" },
  { value: "27-2031", label: "Dancers", text: "Bailarines" },
  { value: "27-2042", label: "Musicians and Singers", text: "Músicos y Cantantes" },
  { value: "27-4021", label: "Photographers", text: "Fotógrafos" },
  { value: "29-1011", label: "Chiropractors", text: "Quiroprácticos" },
  { value: "29-1021", label: "Dentists, General", text: "Dentistas Generales" },
  { value: "29-1022", label: "Oral and Maxillofacial Surgeons", text: "Cirujanos Orales y Maxilofaciales" },
  { value: "29-1023", label: "Orthodontists", text: "Ortodoncistas" },
  { value: "29-1024", label: "Prosthodontists", text: "Prostodoncistas" },
  { value: "29-1029", label: "Dentists, All Other Specialists", text: "Dentistas, Todos los Otros Especialistas" },
  { value: "29-1041", label: "Optometrists", text: "Optometristas" },
  { value: "29-1061", label: "Anesthesiologists", text: "Anestesiólogos" },
  { value: "29-1062", label: "Family and General Practitioners", text: "Médicos de Familia y Médicos Generales" },
  { value: "29-1063", label: "Internists, General", text: "Internistas Generales" },
  { value: "29-1064", label: "Obstetricians and Gynecologists", text: "Obstetras y Ginecólogos" },
  { value: "29-1065", label: "Pediatricians, General", text: "Pediatras Generales" },
  { value: "29-1066", label: "Psychiatrists", text: "Psiquiatras" },
  { value: "29-1067", label: "Surgeons", text: "Cirujanos" },
  { value: "29-1069", label: "Physicians and Surgeons, All Other", text: "Médicos y Cirujanos, Todos los Otros" },
  { value: "29-1081", label: "Podiatrists", text: "Podólogos" },
  { value: "29-1131", label: "Veterinarians", text: "Veterinarios" },
  { value: "29-1199", label: "Health Diagnosing and Treating Practitioners, All Other", text: "Practicionarios de Diagnóstico y Tratamiento de Salud, Todos los Otros" },
  { value: "29-2081", label: "Opticians, Dispensing", text: "Optometristas, Dispensadores" },
  { value: "29-2091", label: "Orthotists and Prosthetists", text: "Ortopedistas y Prótesis" },
  { value: "31-9097", label: "Phlebotomists", text: "Flebotomistas" },
  { value: "33-9021", label: "Private Detectives and Investigators", text: "Detectives Privados y Investigadores" },
  { value: "33-9031", label: "Gaming Surveillance Officers and Gaming Investigators", text: "Oficiales de Vigilancia de Juego e Investigadores de Juego" },
  { value: "35-1011", label: "Chefs and Head Cooks", text: "Cocineros y Jefes de Cocina" },
  { value: "35-3011", label: "Bartenders", text: "Bartenders" },
  { value: "39-1011", label: "Gaming Supervisors", text: "Supervisores de Juego" },
  { value: "39-3011", label: "Gaming Dealers", text: "Jugadores de Juego" },
  { value: "39-3012", label: "Gaming and Sports Book Writers and Runners", text: "Escritores y Corredores de Apuestas Deportivas y de Juego" },
  { value: "39-3019", label: "Gaming Service Workers, All Other", text: "Trabajadores de Servicios de Juego, Todos los Otros" },
  { value: "39-4011", label: "Embalmers", text: "Embaladores" },
  { value: "41-2011", label: "Cashiers", text: "Cajeros" },
  { value: "41-2012", label: "Gaming Change Persons and Booth Cashiers", text: "Cambios de Juego y Cajeros de Cabinas" },
  { value: "41-3021", label: "Insurance Sales Agents", text: "Agentes de Venta de Seguros" },
  { value: "41-3031", label: "Securities, Commodities, and Financial Services Sales Agents", text: "Agentes de Venta de Valores, Materias Primas y Servicios Financieros" },
  { value: "41-3041", label: "Travel Agents", text: "Agentes de Viaje" },
  { value: "41-9012", label: "Models", text: "Modelos" },
  { value: "41-9021", label: "Real Estate Brokers", text: "Corredores de Bienes Raíces" },
  { value: "41-9022", label: "Real Estate Sales Agents", text: "Agentes de Venta de Bienes Raíces" },
  { value: "43-3041", label: "Gaming Cage Workers", text: "Trabajadores de Juego en Caja" },
  { value: "43-3071", label: "Tellers", text: "Cajeros de Cuenta" },
  { value: "43-3099", label: "Financial Clerks, All Other", text: "Oficinistas Financieros, Todos los Otros" },
  { value: "43-4011", label: "Brokerage Clerks", text: "Oficinistas de Corretaje" },
  { value: "43-4181", label: "Reservation and Transportation Ticket Agents and Travel Clerks", text: "Agentes de Reservación y Boletos de Transporte y Oficinistas de Viaje" },
  { value: "43-5011", label: "Cargo and Freight Agents", text: "Agentes de Carga y Transporte" },
  { value: "43-5081", label: "Stock Clerks and Order Fillers", text: "Oficinistas de Inventario y Rellenadores de Órdenes" },
  { value: "43-9041", label: "Insurance Claims and Policy Processing Clerks", text: "Oficinistas de Reclamaciones de Seguros y Procesamiento de Pólizas" },
  { value: "45-2021", label: "Animal Breeders", text: "Criadores de Animales" },
  { value: "47-1011", label: "First-Line Supervisors of Construction Trades and Extraction Workers", text: "Supervisores de Primer Nivel de Trabajos de Construcción y Trabajadores de Extracción" },
  { value: "47-2061", label: "Construction Laborers", text: "Trabajadores Constructivos" },
  { value: "47-2071", label: "Paving, Surfacing, and Tamping Equipment Operators", text: "Operadores de Equipos para Empedrado, Superficie y Compactación" },
  { value: "47-2073", label: "Operating Engineers and Other Construction Equipment Operators", text: "Ingenieros Operadores y Otros Operadores de Equipos de Construcción" },
  { value: "47-2141", label: "Painters, Construction and Maintenance", text: "Pintores, Construcción y Mantenimiento" },
  { value: "47-2152", label: "Plumbers, Pipefitters, and Steamfitters", text: "Plomeros, Instaladores de Tuberías y Soldadores a Vapor" },
  { value: "47-4011", label: "Construction and Building Inspectors", text: "Inspectores de Construcción y Edificios" },
  { value: "47-4099", label: "Construction and Related Workers, All Other", text: "Trabajadores de Construcción y Relacionados, Todos los Otros" },
  { value: "47-5011", label: "Derrick Operators, Oil and Gas", text: "Operadores de Torre de Perforación, Petróleo y Gas" },
  { value: "47-5012", label: "Rotary Drill Operators, Oil and Gas", text: "Operadores de Taladro Rotativo, Petróleo y Gas" },
  { value: "47-5013", label: "Service Unit Operators, Oil, Gas, and Mining", text: "Operadores de Unidad de Servicio, Petróleo, Gas y Minería" },
  { value: "47-5021", label: "Earth Drillers, Except Oil and Gas", text: "Perforadores de Tierra, Excepto Petróleo y Gas" },
  { value: "47-5031", label: "Explosives Workers, Ordnance Handling Experts, and Blasters", text: "Trabajadores de Explosivos, Expertos en Manejo de Armas y Explosivos" },
  { value: "47-5041", label: "Continuous Mining Machine Operators", text: "Operadores de Máquinas Mineras Continuas" },
  { value: "47-5049", label: "Mining Machine Operators, All Other", text: "Operadores de Máquinas Mineras, Todos los Otros" },
  { value: "47-5061", label: "Roof Bolters, Mining", text: "Soldadores de Techos en Minería" },
  { value: "47-5071", label: "Roustabouts, Oil and Gas", text: "Trabajadores de Apoyo, Petróleo y Gas" },
  { value: "47-5099", label: "Extraction Workers, All Other", text: "Trabajadores de Extracción, Todos los Otros" },
  { value: "49-2011", label: "Computer, Automated Teller, and Office Machine Repairers", text: "Reparadores de Computadoras, Cajeros Automáticos y Máquinas de Oficina" },
  { value: "49-2092", label: "Electric Motor, Power Tool, and Related Repairers", text: "Reparadores de Motores Eléctricos, Herramientas Eléctricas y Relacionados" },
  { value: "49-9064", label: "Watch Repairers", text: "Reparadores de Relojes" },
  { value: "49-9091", label: "Coin, Vending, and Amusement Machine Servicers and Repairers", text: "Técnicos y Reparadores de Máquinas de Monedas, Venta Automática y Entretenimiento" },
  { value: "51-4032", label: "Drilling and Boring Machine Tool Setters, Operators, and Tenders", text: "Ajustadores, Operadores y Asistentes de Máquinas para Perforar y Taladrar" },
  { value: "51-8011", label: "Nuclear Power Reactor Operators", text: "Operadores de Reactores de Energía Nuclear" },
  { value: "51-8092", label: "Gas Plant Operators", text: "Operadores de Plantas de Gas" },
  { value: "51-8093", label: "Petroleum Pump System Operators, Refinery Operators", text: "Operadores de Sistemas de Bombeo de Petróleo y Operadores de Refinerías" },
  { value: "51-9071", label: "Jewelers and Precious Stone and Metal Workers", text: "Joyeros y Trabajadores de Piedras Preciosas y Metales" },
  { value: "53-1011", label: "Aircraft Cargo Handling Supervisors", text: "Supervisores de Manejo de Carga Aérea" },
  { value: "53-2011", label: "Airline Pilots, Copilots, and Flight Engineers", text: "Pilotos de Líneas Aéreas, Copilotos e Ingenieros de Vuelo" },
  { value: "53-2012", label: "Commercial Pilots", text: "Pilotos Comerciales" },
  { value: "53-2031", label: "Flight Attendants", text: "Auxiliares de Vuelo" },
  { value: "53-3032", label: "Heavy and Tractor-Trailer Truck Drivers", text: "Conductores de Camiones Pesados y Remolcadores" },
  { value: "53-5011", label: "Sailors and Marine Oilers", text: "Marineros y Aceiteros Marinos" },
  { value: "53-5021", label: "Captains, Mates, and Pilots of Water Vessels", text: "Capitanes, Oficiales y Pilotos de Naves Marinas" },
  { value: "53-5022", label: "Motorboat Operators", text: "Operadores de Barcos Motorizados" },
  { value: "53-6061", label: "Transportation Attendants, Except Flight Attendants", text: "Auxiliares de Transporte, Excepto Auxiliares de Vuelo" },
  { value: "53-6099", label: "Transportation Workers, All Other", text: "Trabajadores de Transporte, Todos los Otros" },
  { value: "53-7033", label: "Loading Machine Operators, Underground Mining", text: "Operadores de Máquinas de Carga, Minería Subterránea" },
  { value: "53-7041", label: "Hoist and Winch Operators", text: "Operadores de Elevadores y Grúas" },
  { value: "53-7062", label: "Laborers and Freight, Stock, and Material Movers, Hand", text: "Trabajadores y Transportistas de Carga, Inventario y Materiales a Mano" },
  { value: "53-7071", label: "Gas Compressor and Gas Pumping Station Operators", text: "Operadores de Compresores de Gas y Estaciones de Bombeo de Gas" },
  { value: "53-7111", label: "Mine Shuttle Car Operators", text: "Operadores de Vagones Subterráneos Mineros" },
  { value: "53-7121", label: "Tank Car, Truck, and Ship Loaders", text: "Cargadores de Tanques, Camiones y Naves Marinas" },
  { value: "55-1011", label: "Air Crew Officers", text: "Oficiales de Tripulación Aérea" },
  { value: "55-1016", label: "Infantry Officers", text: "Oficiales del Infante" },
  { value: "55-1017", label: "Special Forces Officers", text: "Oficiales de Fuerzas Especiales" },
  { value: "55-1019", label: "Military Officer Special and Tactical Operations Leaders", text: "Líderes de Oficiales Militares de Operaciones Especiales y Tácticas" },
  { value: "55-2011", label: "First-Line Supervisors of Air Crew Members", text: "Supervisores de Primera Línea de Miembros de Tripulación Aérea" },
  { value: "55-3011", label: "Air Crew Members", text: "Miembros de Tripulación Aérea" },
  { value: "55-3016", label: "Infantry", text: "Infante" },
  { value: "55-3018", label: "Special Forces", text: "Fuerzas Especiales" },
  { value: "55-3019", label: "Military Enlisted Tactical Operations and Air/Weapons Specialists", text: "Especialistas en Operaciones Tácticas y Armas Aéreas/Militares" },
  { value: "SELFEMP", label: "Self-Employee", text: "Autoempleado" },
  { value: "OTHERXX", label: "Other", text: "Otro" },
  { value: "UNEMPLO", label: "Unemployed", text: "Desempleado" },
  { value: "15-1121", label: "Computer Systems Analysts", text: "Analistas de Sistemas de Computación" },
  { value: "15-1131", label: "Computer Programmers", text: "Programadores de Computación" },
  { value: "15-1132", label: "Software Developers, Applications", text: "Desarrolladores de Software, Aplicaciones" },
  { value: "15-1133", label: "Software Developers, Systems Software", text: "Desarrolladores de Software, Sistemas Operativos" },
  { value: "15-1134", label: "Web Developers", text: "Desarrolladores Web" },
  { value: "15-1141", label: "Database Administrators", text: "Administradores de Bases de Datos" },
  { value: "15-1199", label: "Computer Occupations, All Other", text: "Ocupaciones de Computación, Todas las Otras" },
  { value: "23-2011", label: "Paralegals and Legal Assistants", text: "Paralegales y Asistentes Legales" },
  { value: "27-2099", label: "Entertainers and Performers, Sports and Related Workers", text: "Entretenedores y Artistas, Trabajadores Deportivos y Relacionados" },
  { value: "33-3021", label: "Detectives and Criminal Investigators", text: "Detectives y Investigadores del Crimen" },
  { value: "51-4121", label: "Welders, Cutters, Solderers, and Brazers", text: "Soldadores, Cortadores, Soldadores y Fundidores" },
  { value: "51-4122", label: "Welding, Soldering, and Brazing Machine Setters, Operators", text: "Operadores y Ajustadores de Máquinas de Soldadura, Soldadura y Fundición" },
  { value: "53-3041", label: "Taxi Drivers and Chauffeurs", text: "Taxistas y Choferes de Autos de Alquiler" },
  { value: "53-7073", label: "Wellhead Pumpers", text: "Bombeadores de Pozos" },
  { value: "11-1021", label: "General and Operations Managers", text: "Directores Generales y de Operaciones" },
  { value: "11-2021", label: "Marketing Managers", text: "Directores de Marketing" },
  { value: "11-2022", label: "Sales Managers", text: "Directores de Ventas" },
  { value: "11-3011", label: "Administrative Services Managers", text: "Directores de Servicios Administrativos" },
  { value: "11-3021", label: "Computer and Information Systems Managers", text: "Directores de Sistemas y Tecnología de Información" },
  { value: "11-3061", label: "Purchasing Managers", text: "Directores de Compras" },
  { value: "11-3111", label: "Compensation and Benefits Managers", text: "Directores de Compensación y Beneficios" },
  { value: "11-3121", label: "Human Resources Managers", text: "Directores de Recursos Humanos" },
  { value: "11-3131", label: "Training and Development Managers", text: "Directores de Capacitación y Desarrollo" },
  { value: "11-9013", label: "Farmers, Ranchers, and Other Agricultural Managers", text: "Agricultores, Ganaderos y Otros Directores Agrícolas" },
  { value: "11-9031", label: "Education Administrators, Preschool and Childcare", text: "Administradores de Educación, Preescolar y Cuidado Infantil" },
  { value: "11-9032", label: "Education Administrators, Elementary and Secondary", text: "Administradores de Educación, Primaria y Secundaria" },
  { value: "11-9033", label: "Education Administrators, Postsecondary", text: "Administradores de Educación, Postsecundaria" },
  { value: "11-9039", label: "Education Administrators, All Other", text: "Administradores de Educación, Todos los Otros" },
  { value: "11-9051", label: "Food Service Managers", text: "Directores de Servicios Alimentarios" },
  { value: "11-9061", label: "Funeral Service Managers", text: "Directores de Servicios Funerarios" },
  { value: "11-9081", label: "Lodging Managers", text: "Directores de Alojamientos" },
  { value: "11-9111", label: "Medical and Health Services Managers", text: "Directores de Servicios Médicos y de Salud" },
  { value: "11-9121", label: "Natural Sciences Managers", text: "Directores de Ciencias Naturales" },
  { value: "11-9131", label: "Postmasters and Mail Superintendents", text: "Jefes Postales y Superintendentes de Correo" },
  { value: "11-9151", label: "Social and Community Service Managers", text: "Directores de Servicios Sociales y Comunitarios" },
  { value: "11-9161", label: "Emergency Management Directors", text: "Directores de Gestión de Emergencias" },
  { value: "11-9199", label: "Managers, All Other", text: "Directores, Todos los Otros" },
  { value: "13-1021", label: "Buyers and Purchasing Agents, Farm Products", text: "Compradores y Agentes de Compras, Productos Agrícolas" },
  { value: "13-1022", label: "Wholesale and Retail Buyers, Except Farm Products", text: "Compradores al por Mayor y al por Menor, Excepto Productos Agrícolas" },
  { value: "13-1023", label: "Purchasing Agents, Except Wholesale, Retail, and Farm Products", text: "Agentes de Compras, Excepto al por Mayor, al por Menor y Productos Agrícolas" },
  { value: "13-1031", label: "Claims Adjusters, Examiners, and Investigators", text: "Ajustadores de Reclamos, Examinadores e Investigadores" },
  { value: "13-1032", label: "Insurance Appraisers, Auto Damage", text: "Peritos de Seguros de Daños a Vehículos" },
  { value: "13-1051", label: "Cost Estimators", text: "Estimadores de Costos" },
  { value: "13-1071", label: "Human Resources Specialists", text: "Especialistas en Recursos Humanos" },
  { value: "13-1074", label: "Farm Labor Contractors", text: "Contratistas de Trabajo Agrícola" },
  { value: "13-1075", label: "Labor Relations Specialists", text: "Especialistas en Relaciones Laborales" },
  { value: "13-1081", label: "Logisticians", text: "Logísticos" },
  { value: "13-1111", label: "Management Analysts", text: "Analistas de Gestión" },
  { value: "13-1121", label: "Meeting, Convention, and Event Planners", text: "Planificadores de Reuniones, Convenciones y Eventos" },
  { value: "13-1141", label: "Compensation, Benefits, and Job Analysis Specialists", text: "Especialistas en Compensación, Beneficios y Análisis de Trabajo" },
  { value: "13-1151", label: "Training and Development Specialists", text: "Especialistas en Capacitación y Desarrollo" },
  { value: "13-1161", label: "Market Research Analysts and Marketing Specialists", text: "Analistas de Investigación de Mercado y Especialistas en Marketing" },
  { value: "13-1199", label: "Business Operations Specialists, All Other", text: "Especialistas en Operaciones Empresariales, Todos los Otros" },
  { value: "13-2031", label: "Budget Analysts", text: "Analistas de Presupuestos" },
  { value: "13-2041", label: "Credit Analysts", text: "Analistas de Crédito" },
  { value: "13-2071", label: "Credit Counselors", text: "Consejeros de Crédito" },
  { value: "13-2072", label: "Loan Officers", text: "Oficiales de Préstamo" },
  { value: "15-1111", label: "Computer and Information Research Scientists", text: "Científicos de Computación e Información" },
  { value: "15-1122", label: "Information Security Analysts", text: "Analistas de Seguridad de Información" },
  { value: "15-1142", label: "Network and Computer Systems Administrators", text: "Administradores de Redes y Sistemas Computacionales" },
  { value: "15-1143", label: "Computer Network Architects", text: "Arquitectos de Redes Computacionales" },
  { value: "15-1151", label: "Computer User Support Specialists", text: "Especialistas en Soporte al Usuario Computacional" },
  { value: "15-1152", label: "Computer Network Support Specialists", text: "Especialistas en Soporte a Redes Computacionales" },
  { value: "15-2011", label: "Actuaries", text: "Actuarios" },
  { value: "15-2021", label: "Mathematicians", text: "Matemáticos" },
  { value: "15-2031", label: "Operations Research Analysts", text: "Analistas de Investigación Operativa" },
  { value: "15-2041", label: "Statisticians", text: "Estadísticos" },
  { value: "15-2091", label: "Mathematical Technicians", text: "Técnicos Matemáticos" },
  { value: "15-2099", label: "Mathematical Science Occupations, All Other", text: "Ocupaciones Científicas Matemáticas, Todas las Otras" },
  { value: "17-1011", label: "Architects, Except Landscape and Naval", text: "Arquitectos, Excepto Paisajistas y Navales" },
  { value: "17-1012", label: "Landscape Architects", text: "Arquitectos Paisajistas" },
  { value: "17-1021", label: "Cartographers and Photogrammetrists", text: "Cartógrafos y Fotogrametristas" },
  { value: "17-1022", label: "Surveyors", text: "Topógrafos" },
  { value: "17-2011", label: "Aerospace Engineers", text: "Ingenieros Aeronáuticos" },
  { value: "17-2021", label: "Agricultural Engineers", text: "Ingenieros Agrícolas" },
  { value: "17-2031", label: "Biomedical Engineers", text: "Ingenieros Biomédicos" },
  { value: "17-2041", label: "Chemical Engineers", text: "Ingenieros Químicos" },
  { value: "17-2061", label: "Computer Hardware Engineers", text: "Ingenieros de Hardware Computacional" },
  { value: "17-2071", label: "Electrical Engineers", text: "Ingenieros Eléctricos" },
  { value: "17-2072", label: "Electronics Engineers, Except Computer", text: "Ingenieros Electrónicos, Excepto Computacionales" },
  { value: "17-2081", label: "Environmental Engineers", text: "Ingenieros Ambientales" },
  { value: "17-2111", label: "Health and Safety Engineers, Except Mining Safety", text: "Ingenieros de Salud y Seguridad, Excepto Seguridad Minera" },
  { value: "17-2112", label: "Industrial Engineers", text: "Ingenieros Industriales" },
  { value: "17-2121", label: "Marine Engineers and Naval Architects", text: "Ingenieros Marinos y Arquitectos Navales" },
  { value: "17-2131", label: "Materials Engineers", text: "Ingenieros de Materiales" },
  { value: "17-2141", label: "Mechanical Engineers", text: "Ingenieros Mecánicos" },
  { value: "17-3011", label: "Architectural and Civil Drafters", text: "Dibujantes Arquitectónicos y Civiles" },
  { value: "17-3012", label: "Electrical and Electronics Drafters", text: "Dibujantes Eléctricos y Electrónicos" },
  { value: "17-3013", label: "Mechanical Drafters", text: "Dibujantes Mecánicos" },
  { value: "17-3019", label: "Drafters, All Other", text: "Dibujantes, Todos los Otros" },
  { value: "17-3021", label: "Aerospace Engineering and Operations Technicians", text: "Técnicos de Ingeniería y Operaciones Aeronáuticas" },
  { value: "17-3022", label: "Civil Engineering Technicians", text: "Técnicos de Ingeniería Civil" },
  { value: "17-3023", label: "Electrical and Electronics Engineering Technicians", text: "Técnicos de Ingeniería Eléctrica y Electrónica" },
  { value: "17-3024", label: "Electro-Mechanical Technicians", text: "Técnicos Electro-Mecánicos" },
  { value: "17-3025", label: "Environmental Engineering Technicians", text: "Técnicos de Ingeniería Ambiental" },
  { value: "17-3026", label: "Industrial Engineering Technicians", text: "Técnicos de Ingeniería Industrial" },
  { value: "17-3027", label: "Mechanical Engineering Technicians", text: "Técnicos de Ingeniería Mecánica" },
  { value: "17-3029", label: "Engineering Technicians, Except Drafters, All Other", text: "Técnicos de Ingeniería, Excepto Dibujantes, Todos los Otros" },
  { value: "17-3031", label: "Surveying and Mapping Technicians", text: "Técnicos de Levantamiento y Cartografía" },
  { value: "19-1011", label: "Animal Scientists", text: "Científicos de Animales" },
  { value: "19-1012", label: "Food Scientists and Technologists", text: "Científicos y Tecnólogos de Alimentos" },
  { value: "19-1013", label: "Soil and Plant Scientists", text: "Científicos de Suelo y Plantas" },
  { value: "19-1021", label: "Biochemists and Biophysicists", text: "Bioquímicos y Biófisicos" },
  { value: "19-1022", label: "Microbiologists", text: "Microbiólogos" },
  { value: "19-1023", label: "Zoologists and Wildlife Biologists", text: "Zoológicos y Biólogos de Vida Silvestre" },
  { value: "19-1029", label: "Biological Scientists, All Other", text: "Científicos Biológicos, Todos los Otros" },
  { value: "19-1031", label: "Conservation Scientists", text: "Científicos de Conservación" },
  { value: "19-1032", label: "Foresters", text: "Silvicultores" },
  { value: "19-1042", label: "Medical Scientists, Except Epidemiologists", text: "Científicos Médicos, Excepto Epidemiólogos" },
  { value: "19-1099", label: "Life Scientists, All Other", text: "Científicos de Vida, Todos los Otros" },
  { value: "19-2011", label: "Astronomers", text: "Astrónomos" },
  { value: "19-2012", label: "Physicists", text: "Físicos" },
  { value: "19-2021", label: "Atmospheric and Space Scientists", text: "Científicos Atmosféricos y de Espacio" },
  { value: "19-2031", label: "Chemists", text: "Químicos" },
  { value: "19-2032", label: "Materials Scientists", text: "Científicos de Materiales" },
  { value: "19-2041", label: "Environmental Scientists and Specialists, Including Health", text: "Científicos y Especialistas Ambientales, Incluyendo Salud" },
  { value: "19-2043", label: "Hydrologists", text: "Hidrologistas" },
  { value: "19-2099", label: "Physical Scientists, All Other", text: "Científicos Físicos, Todos los Otros" },
  { value: "19-3022", label: "Survey Researchers", text: "Investigadores de Encuestas" },
  { value: "19-3031", label: "Clinical, Counseling, and School Psychologists", text: "Psicólogos Clínicos, de Consejo y Escolares" },
  { value: "19-3032", label: "Industrial-Organizational Psychologists", text: "Psicólogos Industriales y Organizacionales" },
  { value: "19-3039", label: "Psychologists, All Other", text: "Psicólogos, Todos los Otros" },
  { value: "19-3041", label: "Sociologists", text: "Sociólogos" },
  { value: "19-3051", label: "Urban and Regional Planners", text: "Planificadores Urbanos y Regionales" },
  { value: "19-3091", label: "Anthropologists and Archeologists", text: "Antropólogos y Arqueólogos" },
  { value: "19-3092", label: "Geographers", text: "Geógrafos" },
  { value: "19-3093", label: "Historians", text: "Historiadores" },
  { value: "19-3094", label: "Political Scientists", text: "Científicos Políticos" },
  { value: "19-3099", label: "Social Scientists and Related Workers, All Other", text: "Científicos Sociales y Trabajadores Relacionados, Todos los Otros" },
  { value: "19-4011", label: "Agricultural and Food Science Technicians", text: "Técnicos de Ciencias Agrícolas y Alimentarias" },
  { value: "19-4021", label: "Biological Technicians", text: "Técnicos Biológicos" },
  { value: "19-4031", label: "Chemical Technicians", text: "Técnicos Químicos" },
  { value: "19-4061", label: "Social Science Research Assistants", text: "Asistentes de Investigación en Ciencias Sociales" },
  { value: "19-4091", label: "Environmental Science and Protection Technicians, Including Health", text: "Técnicos de Ciencias Ambientales y Protección, Incluyendo Salud" },
  { value: "19-4092", label: "Forensic Science Technicians", text: "Técnicos de Ciencias Forenses" },
  { value: "19-4093", label: "Forest and Conservation Technicians", text: "Técnicos Forestales y de Conservación" },
  { value: "19-4099", label: "Life, Physical, and Social Science Technicians, All Other", text: "Técnicos de Ciencias de Vida, Físicas y Sociales, Todos los Otros" },
  { value: "21-1011", label: "Substance Abuse and Behavioral Disorder Counselors", text: "Consejeros de Abuso de Sustancias y Trastornos Conductuales" },
  { value: "21-1012", label: "Educational, Guidance, School, and Vocational Counselors", text: "Consejeros Educativos, de Orientación Escolar y Vocacional" },
  { value: "21-1013", label: "Marriage and Family Therapists", text: "Terapeutas de Matrimonio y Familia" },
  { value: "21-1014", label: "Mental Health Counselors", text: "Consejeros de Salud Mental" },
  { value: "21-1015", label: "Rehabilitation Counselors", text: "Consejeros de Rehabilitación" },
  { value: "21-1019", label: "Counselors, All Other", text: "Consejeros, Todos los Otros" },
  { value: "21-1021", label: "Child, Family, and School Social Workers", text: "Trabajadores Sociales de Niños, Familia y Escuela" },
  { value: "21-1022", label: "Healthcare Social Workers", text: "Trabajadores Sociales de Cuidado de Salud" },
  { value: "21-1023", label: "Mental Health and Substance Abuse Social Workers", text: "Trabajadores Sociales de Salud Mental y Abuso de Sustancias" },
  { value: "21-1029", label: "Social Workers, All Other", text: "Trabajadores Sociales, Todos los Otros" },
  { value: "21-1091", label: "Health Educators", text: "Educadores en Salud" },
  { value: "21-1092", label: "Probation Officers and Correctional Treatment Specialists", text: "Oficiales de Probación y Especialistas en Tratamiento Correctivo" },
  { value: "21-1093", label: "Social and Human Service Assistants", text: "Asistentes de Servicios Sociales y Humanos" },
  { value: "21-1094", label: "Community Health Workers", text: "Trabajadores de Salud Comunitaria" },
  { value: "21-1099", label: "Community and Social Service Specialists, All Other", text: "Especialistas en Servicios Sociales y Comunitarios, Todos los Otros" },
  { value: "21-2011", label: "Clergy", text: "Clero" },
  { value: "21-2021", label: "Directors, Religious Activities and Education", text: "Directores de Actividades y Educación Religiosa" },
  { value: "21-2099", label: "Religious Workers, All Other", text: "Trabajadores Religiosos, Todos los Otros" },
  { value: "23-1012", label: "Judicial Law Clerks", text: "Asistentes Legales Judiciales" },
  { value: "23-1022", label: "Arbitrators, Mediators, and Conciliators", text: "Árbitros, Mediadores y Conciliadores" },
  { value: "23-2091", label: "Court Reporters", text: "Reporteros de Tribunal" },
  { value: "23-2093", label: "Title Examiners, Abstractors, and Searchers", text: "Examinadores de Títulos, Abstractores y Buscadores" },
  { value: "23-2099", label: "Legal Support Workers, All Other", text: "Trabajadores de Apoyo Legal, Todos los Otros" },
  { value: "25-1011", label: "Business Teachers, Postsecondary", text: "Profesores de Negocios, Postsecundario" },
  { value: "25-1021", label: "Computer Science Teachers, Postsecondary", text: "Profesores de Ciencias de la Computación, Postsecundario" },
  { value: "25-1022", label: "Mathematical Science Teachers, Postsecondary", text: "Profesores de Ciencias Matemáticas, Postsecundario" },
  { value: "25-1031", label: "Architecture Teachers, Postsecondary", text: "Profesores de Arquitectura, Postsecundario" },
  { value: "25-1032", label: "Engineering Teachers, Postsecondary", text: "Profesores de Ingeniería, Postsecundario" },
  { value: "25-1041", label: "Agricultural Sciences Teachers, Postsecondary", text: "Profesores de Ciencias Agrícolas, Postsecundario" },
  { value: "25-1042", label: "Biological Science Teachers, Postsecondary", text: "Profesores de Ciencias Biológicas, Postsecundario" },
  { value: "25-1043", label: "Forestry and Conservation Science Teachers, Postsecondary", text: "Profesores de Ciencias Forestales y de Conservación, Postsecundario" },
  { value: "25-1051", label: "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary", text: "Profesores de Ciencias Atmosféricas, Terrestres, Marinas y Espaciales, Postsecundario" },
  { value: "25-1052", label: "Chemistry Teachers, Postsecondary", text: "Profesores de Química, Postsecundario" },
  { value: "25-1053", label: "Environmental Science Teachers, Postsecondary", text: "Profesores de Ciencias Ambientales, Postsecundario" },
  { value: "25-1054", label: "Physics Teachers, Postsecondary", text: "Profesores de Física, Postsecundario" },
  { value: "25-1061", label: "Anthropology and Archeology Teachers, Postsecondary", text: "Profesores de Antropología y Arqueología, Postsecundario" },
  { value: "25-1062", label: "Area, Ethnic, and Cultural Studies Teachers, Postsecondary", text: "Profesores de Estudios de Áreas, Étnicos y Culturales, Postsecundario" },
  { value: "25-1063", label: "Economics Teachers, Postsecondary", text: "Profesores de Economía, Postsecundario" },
  { value: "25-1064", label: "Geography Teachers, Postsecondary", text: "Profesores de Geografía, Postsecundario" },
  { value: "25-1065", label: "Political Science Teachers, Postsecondary", text: "Profesores de Ciencia Política, Postsecundario" },
  { value: "25-1066", label: "Psychology Teachers, Postsecondary", text: "Profesores de Psicología, Postsecundario" },
  { value: "25-1067", label: "Sociology Teachers, Postsecondary", text: "Profesores de Sociología, Postsecundario" },
  { value: "25-1069", label: "Social Sciences Teachers, Postsecondary, All Other", text: "Profesores de Ciencias Sociales, Postsecundario, Otros" },
  { value: "25-1071", label: "Health Specialties Teachers, Postsecondary", text: "Profesores de Especialidades Médicas, Postsecundario" },
  { value: "25-1072", label: "Nursing Instructors and Teachers, Postsecondary", text: "Profesores de Enfermería e Instructoras de Enfermería, Postsecundario" },
  { value: "25-1081", label: "Education Teachers, Postsecondary", text: "Profesores de Educación, Postsecundario" },
  { value: "25-1082", label: "Library Science Teachers, Postsecondary", text: "Profesores de Ciencias de la Biblioteca, Postsecundario" },
  { value: "25-1111", label: "Criminal Justice and Law Enforcement Teachers, Postsecondary", text: "Profesores de Justicia Criminal y Aplicación de la Ley, Postsecundario" },
  { value: "25-1112", label: "Law Teachers, Postsecondary", text: "Profesores de Derecho, Postsecundario" },
  { value: "25-1113", label: "Social Work Teachers, Postsecondary", text: "Profesores de Trabajo Social, Postsecundario" },
  { value: "25-1121", label: "Art, Drama, and Music Teachers, Postsecondary", text: "Profesores de Arte, Teatro y Música, Postsecundario" },
  { value: "25-1122", label: "Communications Teachers, Postsecondary", text: "Profesores de Comunicaciones, Postsecundario" },
  { value: "25-1123", label: "English Language and Literature Teachers, Postsecondary", text: "Profesores de Lenguaje y Literatura Inglesa, Postsecundario" },
  { value: "25-1124", label: "Foreign Language and Literature Teachers, Postsecondary", text: "Profesores de Lenguas Extranjeras y Literatura, Postsecundario" },
  { value: "25-1125", label: "History Teachers, Postsecondary", text: "Profesores de Historia, Postsecundario" },
  { value: "25-1126", label: "Philosophy and Religion Teachers, Postsecondary", text: "Profesores de Filosofía y Religión, Postsecundario" },
  { value: "25-1191", label: "Graduate Teaching Assistants", text: "Asistentes de Enseñanza de Posgrado" },
  { value: "25-1192", label: "Home Economics Teachers, Postsecondary", text: "Profesores de Economía Doméstica, Postsecundario" },
  { value: "25-1193", label: "Recreation and Fitness Studies Teachers, Postsecondary", text: "Profesores de Estudios Recreativos y De Acondicionamiento Físico, Postsecundario" },
  { value: "25-1194", label: "Vocational Education Teachers, Postsecondary", text: "Profesores de Educación Vocacional, Postsecundario" },
  { value: "25-1199", label: "Postsecondary Teachers, All Other", text: "Profesores de Postsecundario, Otros" },
  { value: "25-2011", label: "Preschool Teachers, Except Special Education", text: "Profesores de Preescolar, Excepto Educación Especial" },
  { value: "25-2012", label: "Kindergarten Teachers, Except Special Education", text: "Profesores de Jardín de Niños, Excepto Educación Especial" },
  { value: "25-2021", label: "Elementary School Teachers, Except Special Education", text: "Profesores de Escuela Primaria, Excepto Educación Especial" },
  { value: "25-2022", label: "Middle School Teachers, Except Special and Career/Technical Education", text: "Profesores de Escuela Secundaria, Excepto Educación Especial y Vocacional/Técnica" },
  { value: "25-2023", label: "Career/Technical Education Teachers, Middle School", text: "Profesores de Educación Vocacional/Técnica, Escuela Secundaria" },
  { value: "25-2031", label: "Secondary School Teachers, Except Special and Career/Technical", text: "Profesores de Escuela Secundaria, Excepto Educación Especial y Vocacional/Técnica" },
  { value: "25-2032", label: "Career/Technical Education Teachers, Secondary School", text: "Profesores de Educación Vocacional/Técnica, Escuela Secundaria" },
  { value: "25-2051", label: "Special Education Teachers, Preschool", text: "Profesores de Educación Especial, Preescolar" },
  { value: "25-2052", label: "Special Education Teachers, Kindergarten and Elementary School", text: "Profesores de Educación Especial, Jardín de Niños y Escuela Primaria" },
  { value: "25-2053", label: "Special Education Teachers, Middle School", text: "Profesores de Educación Especial, Escuela Secundaria" },
  { value: "25-2054", label: "Special Education Teachers, Secondary School", text: "Profesores de Educación Especial, Escuela Secundaria" },
  { value: "25-2059", label: "Special Education Teachers, All Other", text: "Profesores de Educación Especial, Otros" },
  { value: "25-3011", label: "Adult Basic and Secondary Education and Literacy Teachers and Instructors", text: "Profesores y Asistentes de Educación Básica y Secundaria para Adultos y Alfabetización" },
  { value: "25-3021", label: "Self-Enrichment Education Teachers", text: "Profesores de Educación de Autoenriqucimiento" },
  { value: "25-3099", label: "Teachers and Instructors, All Other", text: "Profesores y Asistentes, Otros" },
  { value: "25-4011", label: "Archivists", text: "Archivistas" },
  { value: "25-4013", label: "Museum Technicians and Conservators", text: "Técnicos y Conservadores de Museos" },
  { value: "25-4021", label: "Librarians", text: "Bibliotecarios" },
  { value: "25-4031", label: "Library Technicians", text: "Técnicos de Bibliotecas" },
  { value: "25-9011", label: "Audio-Visual and Multimedia Collections Specialists", text: "Especialistas en Colecciones Audiovisuales y Multimedia" },
  { value: "25-9021", label: "Farm and Home Management Advisors", text: "Asesores de Gestión de Granjas y Hogares" },
  { value: "25-9031", label: "Instructional Coordinators", text: "Coordinadores de Instrucción" },
  { value: "25-9041", label: "Teacher Assistants", text: "Asistentes de Profesores" },
  { value: "25-9099", label: "Education, Training, and Library Workers, All Other", text: "Trabajadores de Educación, Entrenamiento y Bibliotecas, Otros" },
  { value: "27-1014", label: "Multimedia Artists and Animators", text: "Artistas y Animadores Multimedia" },
  { value: "27-1022", label: "Fashion Designers", text: "Diseñadores de Moda" },
  { value: "27-1023", label: "Floral Designers", text: "Diseñadores de Flores" },
  { value: "27-1024", label: "Graphic Designers", text: "Diseñadores Gráficos" },
  { value: "27-1025", label: "Interior Designers", text: "Diseñadores de Interiores" },
  { value: "27-1026", label: "Merchandise Displayers and Window Trimmers", text: "Mostradores de Mercancía y Cortadores de Ventanas" },
  { value: "27-1027", label: "Set and Exhibit Designers", text: "Diseñadores de Escenarios y Exposiciones" },
  { value: "27-1029", label: "Designers, All Other", text: "Diseñadores, Otros" },
  { value: "27-2011", label: "Actors", text: "Actores" },
  { value: "27-2032", label: "Choreographers", text: "Coreógrafos" },
  { value: "27-2041", label: "Music Directors and Composers", text: "Directores y Compositores Musicales" },
  { value: "27-3011", label: "Radio and Television Announcers", text: "Locutores de Radio y Televisión" },
  { value: "27-3012", label: "Public Address System and Other Announcers", text: "Sistemas de Difusión Pública y Otros Locutores" },
  { value: "27-3021", label: "Broadcast News Analysts", text: "Analistas de Noticias en Transmisión" },
  { value: "27-3022", label: "Reporters and Correspondents", text: "Periodistas y Corresponsales" },
  { value: "27-3031", label: "Public Relations Specialists", text: "Especialistas en Relaciones Públicas" },
  { value: "27-3041", label: "Editors", text: "Editores" },
  { value: "27-3042", label: "Technical Writers", text: "Escritores Técnicos" },
  { value: "27-3043", label: "Writers and Authors", text: "Escritores y Autores" },
  { value: "27-3091", label: "Interpreters and Translators", text: "Intérpretes y Traductores" },
  { value: "27-3099", label: "Media and Communication Workers, All Other", text: "Trabajadores de Medios y Comunicación, Otros" },
  { value: "27-4011", label: "Audio and Video Equipment Technicians", text: "Técnicos de Equipos de Audio y Video" },
  { value: "27-4012", label: "Broadcast Technicians", text: "Técnicos de Transmisión" },
  { value: "27-4013", label: "Radio Operators", text: "Operadores de Radio" },
  { value: "27-4014", label: "Sound Engineering Technicians", text: "Técnicos de Ingeniería Sonora" },
  { value: "27-4031", label: "Camera Operators, Television, Video, and Motion Picture", text: "Operadores de Cámara, Televisión, Video y Cine" },
  { value: "27-4032", label: "Film and Video Editors", text: "Editores de Películas y Videos" },
  { value: "27-4099", label: "Media and Communication Equipment Workers, All Other", text: "Trabajadores de Equipos de Medios y Comunicación, Otros" },
  { value: "29-1031", label: "Dietitians and Nutritionists", text: "Dietistas y Nutricionistas" },
  { value: "29-1051", label: "Pharmacists", text: "Farmacéuticos" },
  { value: "29-1071", label: "Physician Assistants", text: "Asistentes Médicos" },
  { value: "29-1122", label: "Occupational Therapists", text: "Terapeutas Ocupacionales" },
  { value: "29-1123", label: "Physical Therapists", text: "Terapeutas Físicos" },
  { value: "29-1124", label: "Radiation Therapists", text: "Terapeutas Radiológicos" },
  { value: "29-1125", label: "Recreational Therapists", text: "Terapeutas Recreativos" },
  { value: "29-1126", label: "Respiratory Therapists", text: "Terapeutas Respiratorios" },
  { value: "29-1127", label: "Speech-Language Pathologists", text: "Patólogos del Lenguaje y la Voz" },
  { value: "29-1128", label: "Exercise Physiologists", text: "Fisiólogos del Ejercicio" },
  { value: "29-1129", label: "Therapists, All Other", text: "Terapeutas, Otros" },
  { value: "29-1141", label: "Registered Nurses", text: "Enfermeras Registradas" },
  { value: "29-1151", label: "Nurse Anesthetists", text: "Anestesistas Enfermeras" },
  { value: "29-1161", label: "Nurse Midwives", text: "Parteras Enfermeras" },
  { value: "29-1171", label: "Nurse Practitioners", text: "Practicantes de Enfermería" },
  { value: "29-1181", label: "Audiologists", text: "Audiólogos" },
  { value: "29-2011", label: "Medical and Clinical Laboratory Technologists", text: "Tecnólogos y Tecnólogas de Laboratorio Médico y Clínico" },
  { value: "29-2012", label: "Medical and Clinical Laboratory Technicians", text: "Técnicos y Técnicas de Laboratorio Médico y Clínico" },
  { value: "29-2021", label: "Dental Hygienists", text: "Higienistas Dentales" },
  { value: "29-2031", label: "Cardiovascular Technologists and Technicians", text: "Tecnólogos y Técnicos Cardiovasculares" },
  { value: "29-2032", label: "Diagnostic Medical Sonographers", text: "Sonógrafos Médicos Diagnósticos" },
  { value: "29-2033", label: "Nuclear Medicine Technologists", text: "Tecnólogos de Medicina Nuclear" },
  { value: "29-2034", label: "Radiologic Technologists", text: "Tecnólogos Radiológicos" },
  { value: "29-2035", label: "Magnetic Resonance Imaging Technologists", text: "Tecnólogos de Imagen por Resonancia Magnética" },
  { value: "29-2041", label: "Emergency Medical Technicians and Paramedics", text: "Técnicos de Emergencia Médica y Paramédicos" },
  { value: "29-2051", label: "Dietetic Technicians", text: "Técnicos Dietéticos" },
  { value: "29-2052", label: "Pharmacy Technicians", text: "Técnicos Farmacéuticos" },
  { value: "29-2053", label: "Psychiatric Technicians", text: "Técnicos Psiquiátricos" },
  { value: "29-2054", label: "Respiratory Therapy Technicians", text: "Técnicos de Terapia Respiratoria" },
  { value: "29-2055", label: "Surgical Technologists", text: "Tecnólogos Cirujanos" },
  { value: "29-2056", label: "Veterinary Technologists and Technicians", text: "Tecnólogos y Técnicos Veterinarios" },
  { value: "29-2057", label: "Ophthalmic Medical Technicians", text: "Técnicos Médicos Oftalmológicos" },
  { value: "29-2061", label: "Licensed Practical and Licensed Vocational Nurses", text: "Enfermeras Practicantes y Enfermeras Vocacionales Licenciadas" },
  { value: "29-2071", label: "Medical Records and Health Information Technicians", text: "Técnicos de Registros Médicos e Información de Salud" },
  { value: "29-2092", label: "Hearing Aid Specialists", text: "Especialistas en Ayudas Auditivas" },
  { value: "29-2099", label: "Health Technologists and Technicians, All Other", text: "Tecnólogos y Técnicos de Salud, Otros" },
  { value: "29-9011", label: "Occupational Health and Safety Specialists", text: "Especialistas en Salud y Seguridad Ocupacional" },
  { value: "29-9012", label: "Occupational Health and Safety Technicians", text: "Técnicos en Salud y Seguridad Ocupacional" },
  { value: "29-9091", label: "Athletic Trainers", text: "Entrenadores Deportivos" },
  { value: "29-9092", label: "Genetic Counselors", text: "Consejeros Genéticos" },
  { value: "29-9099", label: "Healthcare Practitioners and Technical Workers, All Other", text: "Practicantes y Trabajadores Técnicos de la Salud, Otros" },
  { value: "31-1011", label: "Home Health Aides", text: "Asistentes de Cuidados de Salud en el Hogar" },
  { value: "31-1013", label: "Psychiatric Aides", text: "Asistentes Psiquiátricos" },
  { value: "31-1014", label: "Nursing Assistants", text: "Asistentes de Enfermería" },
  { value: "31-1015", label: "Orderlies", text: "Ordenanzas" },
  { value: "31-2011", label: "Occupational Therapy Assistants", text: "Asistentes de Terapia Ocupacional" },
  { value: "31-2012", label: "Occupational Therapy Aides", text: "Asistentes de Terapia Ocupacional" },
  { value: "31-2021", label: "Physical Therapist Assistants", text: "Asistentes de Fisioterapia" },
  { value: "31-2022", label: "Physical Therapist Aides", text: "Asistentes de Fisioterapia" },
  { value: "31-9011", label: "Massage Therapists", text: "Terapeutas Masajistas" },
  { value: "31-9091", label: "Dental Assistants", text: "Asistentes Dentales" },
  { value: "31-9092", label: "Medical Assistants", text: "Asistentes Médicos" },
  { value: "31-9093", label: "Medical Equipment Preparers", text: "Preparadores de Equipos Médicos" },
  { value: "31-9094", label: "Medical Transcriptionists", text: "Transcriptores Médicos" },
  { value: "31-9095", label: "Pharmacy Aides", text: "Asistentes Farmacéuticos" },
  { value: "31-9096", label: "Veterinary Assistants and Laboratory Animal Caretakers", text: "Asistentes Veterinarios y Cuidadores de Animales de Laboratorio" },
  { value: "33-9032", label: "Security Guards", text: "Guardias de Seguridad" },
  { value: "33-9091", label: "Crossing Guards", text: "Guardias de Cruce" },
  { value: "33-9092", label: "Lifeguards, Ski Patrol, and Other Recreational Professionals", text: "Guardavidas, Patrullas de Esquí y Otros Profesionales Recreativos" },
  { value: "33-9093", label: "Transportation Security Screeners", text: "Inspectores de Seguridad del Transporte" },
  { value: "33-9099", label: "Protective Service Workers, All Other", text: "Trabajadores de Servicios de Protección, Otros" },
  { value: "35-1012", label: "First-Line Supervisors of Food Preparation and Serving Workers", text: "Supervisores de Primer Nivel de Trabajadores de Preparación y Servicio de Comida" },
  { value: "35-2011", label: "Cooks, Fast Food", text: "Cocineros, Comida Rápida" },
  { value: "35-2012", label: "Cooks, Institution and Cafeteria", text: "Cocineros, Institución y Cafetería" },
  { value: "35-2013", label: "Cooks, Private Household", text: "Cocineros, Hogar Privado" },
  { value: "35-2014", label: "Cooks, Restaurant", text: "Cocineros, Restaurante" },
  { value: "35-2015", label: "Cooks, Short Order", text: "Cocineros, Pedidos Cortos" },
  { value: "35-2019", label: "Cooks, All Other", text: "Cocineros, Otros" },
  { value: "35-2021", label: "Food Preparation Workers", text: "Trabajadores de Preparación de Comida" },
  { value: "35-3021", label: "Combined Food Preparation and Serving Workers, Including Fast Food", text: "Trabajadores Combinados de Preparación y Servicio de Comida, Incluyendo Comida Rápida" },
  { value: "35-3022", label: "Counter Attendants, Cafeteria, Food Concession, and Coffee Shop", text: "Atendedores de Contador, Cafetería, Concesiones de Comida y Tiendas de Café" },
  { value: "35-3031", label: "Waiters and Waitresses", text: "Meseros y Meseras" },
  { value: "35-3041", label: "Food Servers, Nonrestaurant", text: "Servidores de Comida, No Restaurante" },
  { value: "35-9011", label: "Dining Room and Cafeteria Attendants and Bartender Helpers", text: "Atendedores de Sala de Comidas y Cafetería y Ayudantes de Barman" },
  { value: "35-9021", label: "Dishwashers", text: "Lavaplatos" },
  { value: "35-9031", label: "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop", text: "Anfitriones y Anfitrionas, Restaurante, Salón y Tienda de Café" },
  { value: "35-9099", label: "Food Preparation and Serving Related Workers, All Other", text: "Trabajadores Relacionados con Preparación y Servicio de Comida, Otros" },
  { value: "37-1011", label: "First-Line Supervisors of Housekeeping and Janitorial Workers", text: "Supervisores de Primer Nivel de Trabajadores de Limpieza y Mantenimiento" },
  { value: "37-1012", label: "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping", text: "Supervisores de Primer Nivel de Paisajismo, Servicio de Césped y Mantenimiento de Terrenos" },
  { value: "37-2011", label: "Janitors and Cleaners, Except Maids and Housekeeping Cleaners", text: "Peluqueros y Limpiadores, Excepto Empleadas Domésticas y Limpiadores de Hogar" },
  { value: "37-2012", label: "Maids and Housekeeping Cleaners", text: "Empleadas Domésticas y Limpiadores de Hogar" },
  { value: "39-5011", label: "Barbers", text: "Barberos" },
  { value: "39-5012", label: "Hairdressers, Hairstylists, and Cosmetologists", text: "Peluqueros, Estilistas y Cosmetólogos" },
  { value: "39-5091", label: "Makeup Artists, Theatrical and Performance", text: "Artistas de Maquillaje, Teatral y de Desempeño" },
  { value: "39-5092", label: "Manicurists and Pedicurists", text: "Manicuristas y Pedicuristas" },
  { value: "39-5093", label: "Shampooers", text: "Lavadores de Cabello" },
  { value: "39-5094", label: "Skincare Specialists", text: "Especialistas en Cuidado de la Piel" },
  { value: "39-6011", label: "Baggage Porters and Bellhops", text: "Porteros de Equipaje y Camilleros" },
  { value: "39-6012", label: "Concierges", text: "Conserjes" },
  { value: "39-7011", label: "Tour Guides and Escorts", text: "Guías Turísticas y Escoltas" },
  { value: "39-7012", label: "Travel Guides", text: "Guías de Viaje" },
  { value: "39-9011", label: "Childcare Workers", text: "Trabajadores de Cuidado Infantil" },
  { value: "39-9021", label: "Personal Care Aides", text: "Ayudantes de Cuidado Personal" },
  { value: "39-9031", label: "Fitness Trainers and Aerobics Instructors", text: "Entrenadores de Fitness y Instructores de Aeróbicos" },
  { value: "39-9032", label: "Recreation Workers", text: "Trabajadores de Recreación" },
  { value: "39-9041", label: "Residential Advisors", text: "Asesores Residenciales" },
  { value: "39-9099", label: "Personal Care and Service Workers, All Other", text: "Trabajadores de Cuidado Personal y Servicio, Otros" },
  { value: "41-1011", label: "First-Line Supervisors of Retail Sales Workers", text: "Supervisores de Primer Nivel de Trabajadores de Ventas al Por Menor" },
  { value: "41-1012", label: "First-Line Supervisors of Non-Retail Sales Workers", text: "Supervisores de Primer Nivel de Trabajadores de Ventas No al Por Menor" },
  { value: "41-2021", label: "Counter and Rental Clerks", text: "Clerks de Contador y Alquiler" },
  { value: "41-2022", label: "Parts Salespersons", text: "Vendedores de Piezas" },
  { value: "41-2031", label: "Retail Salespersons", text: "Vendedores al Por Menor" },
  { value: "41-3011", label: "Advertising Sales Agents", text: "Agentes de Ventas de Publicidad" },
  { value: "41-3099", label: "Sales Representatives, Services, All Other", text: "Representantes de Ventas, Servicios, Otros" },
  { value: "41-4011", label: "Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products", text: "Representantes de Ventas, Mayoreo y Fabricación, Productos Técnicos y Científicos" },
  { value: "41-4012", label: "Sales Representatives, Wholesale and Manufacturing, Except Technical", text: "Representantes de Ventas, Mayoreo y Fabricación, Excepto Técnicos" },
  { value: "41-9011", label: "Demonstrators and Product Promoters", text: "Demostradores y Promotores de Productos" },
  { value: "41-9031", label: "Sales Engineers", text: "Ingenieros de Ventas" },
  { value: "41-9041", label: "Telemarketers", text: "Teleoperadores de Ventas" },
  { value: "41-9091", label: "Door-to-Door Sales Workers, News and Street Vendors", text: "Trabajadores de Ventas Puerta a Puerta, Noticias y Vendedores de Calle" },
  { value: "43-4061", label: "Eligibility Interviewers, Government Programs", text: "Entrevistadores de Elegibilidad, Programas del Gobierno" },
  { value: "43-4071", label: "File Clerks", text: "Clerks de Archivos" },
  { value: "43-4081", label: "Hotel, Motel, and Resort Desk Clerks", text: "Clerks de Recepción de Hoteles, Motels y Resorts" },
  { value: "43-4111", label: "Interviewers, Except Eligibility and Loan", text: "Entrevistadores, Excepto Elegibilidad y Préstamos" },
  { value: "43-4121", label: "Library Assistants, Clerical", text: "Asistentes de Biblioteca, Clérigos" },
  { value: "43-4131", label: "Loan Interviewers and Clerks", text: "Entrevistadores y Clerks de Préstamos" },
  { value: "43-4141", label: "New Accounts Clerks", text: "Clerks de Nuevas Cuentas" },
  { value: "43-4151", label: "Order Clerks", text: "Clerks de Órdenes" },
  { value: "43-4161", label: "Human Resources Assistants, Except Payroll and Timekeeping", text: "Asistentes de Recursos Humanos, Excepto Nómina y Control de Tiempo" },
  { value: "43-4171", label: "Receptionists and Information Clerks", text: "Recepcionistas y Clerks de Información" },
  { value: "43-4199", label: "Information and Record Clerks, All Other", text: "Clerks de Información y Registro, Otros" },
  { value: "43-5021", label: "Couriers and Messengers", text: "Mensajeros y Repartidores" },
  { value: "43-5031", label: "Police, Fire, and Ambulance Dispatchers", text: "Despachadores de Policía, Bomberos y Ambulancias" },
  { value: "43-5032", label: "Dispatchers, Except Police, Fire, and Ambulance", text: "Despachadores, Excepto Policía, Bomberos y Ambulancias" },
  { value: "43-5041", label: "Meter Readers, Utilities", text: "Lectores de Medidores, Utilidades" },
  { value: "43-5051", label: "Postal Service Clerks", text: "Clerks del Servicio Postal" },
  { value: "43-5052", label: "Postal Service Mail Carriers", text: "Repartidores del Servicio Postal" },
  { value: "43-5053", label: "Postal Service Mail Sorters, Processors, and Processing Machine Operators", text: "Clasificadores, Procesadores y Operadores de Máquinas de Procesamiento de Correo del Servicio Postal" },
  { value: "43-5061", label: "Production, Planning, and Expediting Clerks", text: "Clerks de Producción, Planificación y Expedición" },
  { value: "43-5071", label: "Shipping, Receiving, and Traffic Clerks", text: "Clerks de Envío, Recepción y Tráfico" },
  { value: "43-5111", label: "Weighers, Measurers, Checkers, and Samplers, Recordkeeping", text: "Pesadores, Medidores, Verificadores y Muestreadores de Registro" },
  { value: "43-6011", label: "Executive Secretaries and Executive Administrative Assistants", text: "Secretarias Ejecutivas y Asistentes Administrativos Ejecutivos" },
  { value: "43-6012", label: "Legal Secretaries", text: "Secretarias Legales" },
  { value: "43-6013", label: "Medical Secretaries", text: "Secretarias Médicas" },
  { value: "43-6014", label: "Secretaries and Administrative Assistants, Except Legal, Medical", text: "Secretarias y Asistentes Administrativos, Excepto Legales y Médicos" },
  { value: "45-3021", label: "Hunters and Trappers", text: "Cazadores y Traperos" },
  { value: "45-4011", label: "Forest and Conservation Workers", text: "Trabajadores de Bosques y Conservación" },
  { value: "45-4021", label: "Fallers", text: "Trabajadores de Corte de Árboles" },
  { value: "45-4022", label: "Logging Equipment Operators", text: "Operadores de Equipos de Tala" },
  { value: "45-4023", label: "Log Graders and Scalers", text: "Clasificadores y Escalers de Leña" },
  { value: "45-4029", label: "Logging Workers, All Other", text: "Trabajadores de Tala, Otros" },
  { value: "47-2011", label: "Boilermakers", text: "Hornilleros" },
  { value: "47-2021", label: "Brickmasons and Blockmasons", text: "Albañiles de Ladrillo y Bloque" },
  { value: "47-2022", label: "Stonemasons", text: "Albañiles de Piedra" },
  { value: "47-2031", label: "Carpenters", text: "Carpinteros" },
  { value: "47-2041", label: "Carpet Installers", text: "Instaladores de Alfombras" },
  { value: "47-2042", label: "Floor Layers, Except Carpet, Wood, and Hard Tiles", text: "Capas de Piso, Excepto Alfombras, Madera y Baldosas Duras" },
  { value: "47-2043", label: "Floor Sanders and Finishers", text: "Aplanadores y Terminadores de Piso" },
  { value: "47-2044", label: "Tile and Marble Setters", text: "Colocadores de Baldosas y Mármol" },
  { value: "47-2051", label: "Cement Masons and Concrete Finishers", text: "Albañiles de Cemento y Terminadores de Concreto" },
  { value: "47-2053", label: "Terrazzo Workers and Finishers", text: "Trabajadores de Terrazzo y Terminadores" },
  { value: "47-2072", label: "Pile-Driver Operators", text: "Operadores de Pila" },
  { value: "47-2081", label: "Drywall and Ceiling Tile Installers", text: "Instaladores de Tablones Secos y Baldosas de Techo" },
  { value: "47-2082", label: "Tapers", text: "Tapers (Trabajadores que terminan superficies)" },
  { value: "47-2111", label: "Electricians", text: "Electricistas" },
  { value: "47-2121", label: "Glaziers", text: "Vidrieros" },
  { value: "47-2131", label: "Insulation Workers, Floor, Ceiling, and Wall", text: "Trabajadores de Aislamiento, Piso, Techo y Paredes" },
  { value: "47-2132", label: "Insulation Workers, Mechanical", text: "Trabajadores de Aislamiento Mecánico" },
  { value: "47-2142", label: "Paperhangers", text: "Pegadores de Papel" },
  { value: "47-2151", label: "Pipelayers", text: "Colocadores de Tuberías" },
  { value: "47-2161", label: "Plasterers and Stucco Masons", text: "Endaradores y Albañiles de Estuco" },
  { value: "47-2171", label: "Reinforcing Iron and Rebar Workers", text: "Trabajadores de Hierro Reforzante y Barra de Refuerzo" },
  { value: "47-2181", label: "Roofers", text: "Techadores" },
  { value: "47-2211", label: "Sheet Metal Workers", text: "Trabajadores de Metal Laminado" },
  { value: "47-2221", label: "Structural Iron and Steel Workers", text: "Trabajadores de Hierro y Acero Estructural" },
  { value: "47-2231", label: "Solar Photovoltaic Installers", text: "Instaladores de Sistemas Fotovoltaicos Solares" },
  { value: "47-3011", label: "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile", text: "Ayudantes--Albañiles de Ladrillo, Bloque, Piedra y Baldosas" },
  { value: "47-3012", label: "Helpers--Carpenters", text: "Ayudantes--Carpinteros" },
  { value: "47-4071", label: "Septic Tank Servicers and Sewer Pipe Cleaners", text: "Servidores de Tanques Sépticos y Limpiadores de Tuberías de Alcantarillado" },
  { value: "47-4091", label: "Segmental Pavers", text: "Pavimentadores Segmentados" },
  { value: "47-5042", label: "Mine Cutting and Channeling Machine Operators", text: "Operadores de Máquinas de Corte y Canalización de Minas" },
  { value: "47-5051", label: "Rock Splitters, Quarry", text: "Divisores de Rocas, Cantera" },
  { value: "47-5081", label: "Helpers--Extraction Workers", text: "Ayudantes--Trabajadores de Extracción" },
  { value: "49-1011", label: "First-Line Supervisors of Mechanics, Installers, and Repairers", text: "Supervisores de Primer Nivel de Mecánicos, Instaladores y Reparadores" },
  { value: "49-2021", label: "Radio, Cellular, and Tower Equipment Installers and Repairers", text: "Instaladores y Reparadores de Equipos de Radio, Celular y Torre" },
  { value: "49-2022", label: "Telecommunications Equipment Installers and Repairers", text: "Instaladores y Reparadores de Equipos de Telecomunicaciones" },
  { value: "49-2091", label: "Avionics Technicians", text: "Técnicos de Aviación Electrónica" },
  { value: "49-2093", label: "Electrical and Electronics Installers and Repairers, Equipment", text: "Instaladores y Reparadores Eléctricos y Electrónicos, Equipos" },
  { value: "49-2094", label: "Electrical and Electronics Repairers, Commercial and Industrial", text: "Reparadores Eléctricos y Electrónicos, Comercial e Industrial" },
  { value: "49-2095", label: "Electrical and Electronics Repairers, Powerhouse, Substation", text: "Reparadores Eléctricos y Electrónicos, Central Eléctrica, Subestación" },
  { value: "49-2096", label: "Electronic Equipment Installers and Repairers, Motor Vehicles", text: "Instaladores y Reparadores de Equipos Electrónicos, Vehículos Motorizados" },
  { value: "49-2097", label: "Electronic Home Entertainment Equipment Installers and Repairers", text: "Instaladores y Reparadores de Equipos de Entretenimiento Doméstico Electrónicos" },
  { value: "49-2098", label: "Security and Fire Alarm Systems Installers", text: "Instaladores de Sistemas de Seguridad y Alarmas contra Incendios" },
  { value: "49-3011", label: "Aircraft Mechanics and Service Technicians", text: "Mecánicos y Técnicos de Servicio de Aeronaves" },
  { value: "49-3021", label: "Automotive Body and Related Repairers", text: "Reparadores de Carrocerías Automotrices y Relacionados" },
  { value: "49-3022", label: "Automotive Glass Installers and Repairers", text: "Instaladores y Reparadores de Vidrios Automotrices" },
  { value: "49-3023", label: "Automotive Service Technicians and Mechanics", text: "Técnicos de Servicio y Mecánicos Automotrices" },
  { value: "49-3031", label: "Bus and Truck Mechanics and Diesel Engine Specialists", text: "Mecánicos de Autobuses y Camiones y Especialistas en Motores Diésel" },
  { value: "49-3041", label: "Farm Equipment Mechanics and Service Technicians", text: "Mecánicos y Técnicos de Servicio de Equipos Agrícolas" },
  { value: "49-9071", label: "Maintenance and Repair Workers, General", text: "Trabajadores de Mantenimiento y Reparación, General" },
  { value: "49-9081", label: "Wind Turbine Service Technicians", text: "Técnicos de Servicio de Turbinas Eólicas" },
  { value: "49-9092", label: "Commercial Divers", text: "Buzos Comerciales" },
  { value: "49-9093", label: "Fabric Menders, Except Garment", text: "Reparadores de Telas, Excepto Ropa" },
  { value: "49-9094", label: "Locksmiths and Safe Repairers", text: "Cerrajeros y Reparadores de Cajas Fuertes" },
  { value: "49-9095", label: "Manufactured Building and Mobile Home Installers", text: "Instaladores de Edificios Manufacturados y Casas Móviles" },
  { value: "49-9096", label: "Riggers", text: "Ajustadores de Cargas" },
  { value: "49-9097", label: "Signal and Track Switch Repairers", text: "Reparadores de Señales y Cambios de Vías" },
  { value: "49-9098", label: "Helpers--Installation, Maintenance, and Repair Workers", text: "Ayudantes--Trabajadores de Instalación, Mantenimiento y Reparación" },
  { value: "49-9099", label: "Installation, Maintenance, and Repair Workers, All Other", text: "Trabajadores de Instalación, Mantenimiento y Reparación, Todos los Otros" },
  { value: "51-1011", label: "First-Line Supervisors of Production and Operating Workers", text: "Supervisores de Primer Nivel de Trabajadores de Producción y Operación" },
  { value: "51-2011", label: "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers", text: "Ensambladores de Estructuras Aéreas, Superficies, Equipos y Sistemas" },
  { value: "51-2021", label: "Coil Winders, Tapers, and Finishers", text: "Enrolladores de Bobinas, Reductores y Terminadores" },
  { value: "51-2022", label: "Electrical and Electronic Equipment Assemblers", text: "Ensambladores de Equipos Eléctricos y Electrónicos" },
  { value: "51-2023", label: "Electromechanical Equipment Assemblers", text: "Ensambladores de Equipos Electromecánicos" },
  { value: "51-2031", label: "Engine and Other Machine Assemblers", text: "Ensambladores de Motores y Otros Equipos Mecánicos" },
  { value: "51-2041", label: "Structural Metal Fabricators and Fitters", text: "Fabricadores y Ajustadores de Metal Estructural" },
  { value: "51-2091", label: "Fiberglass Laminators and Fabricators", text: "Laminadores y Fabricantes de Fibra de Vidrio" },
  { value: "51-2092", label: "Team Assemblers", text: "Ensambladores de Equipos" },
  { value: "51-2093", label: "Timing Device Assemblers and Adjusters", text: "Ensambladores y Ajustadores de Dispositivos Temporizadores" },
  { value: "51-2099", label: "Assemblers and Fabricators, All Other", text: "Ensambladores y Fabricantes, Todos los Otros" },
  { value: "51-3011", label: "Bakers", text: "Panaderos" },
  { value: "51-3021", label: "Butchers and Meat Cutters", text: "Carniceros y Cortadores de Carnes" },
  { value: "51-3022", label: "Meat, Poultry, and Fish Cutters and Trimmers", text: "Cortadores y Ajustadores de Carnes, Pollos y Pescado" },
  { value: "51-3023", label: "Slaughterers and Meat Packers", text: "Degolladores y Empacadores de Carnes" },
  { value: "51-4071", label: "Foundry Mold and Coremakers", text: "Creadores de Moldes y Núcleos de Fundición" },
  { value: "51-4072", label: "Molding, Coremaking, and Casting Machine Setters, Operators", text: "Configuradores, Operadores y Ajustadores de Máquinas de Moldeo, Núcleo y Fundición" },
  { value: "51-4081", label: "Multiple Machine Tool Setters, Operators, and Tenders", text: "Configuradores, Operadores y Ajustadores de Herramientas Múltiples" },
  { value: "51-4111", label: "Tool and Die Makers", text: "Fabricantes de Herramientas y Moldes" },
  { value: "51-4191", label: "Heat Treating Equipment Setters, Operators, and Tenders", text: "Configuradores, Operadores y Ajustadores de Equipos de Tratamiento Térmico" },
  { value: "51-4192", label: "Layout Workers, Metal and Plastic", text: "Trabajadores de Diseño de Metal y Plástico" },
  { value: "51-4193", label: "Plating and Coating Machine Setters, Operators, and Tenders", text: "Configuradores, Operadores y Ajustadores de Máquinas de Recubrimiento y Pintura" },
  { value: "51-4194", label: "Tool Grinders, Filers, and Sharpeners", text: "Pulidores, Afiladores y Afiladores de Herramientas" },
  { value: "51-4199", label: "Metal Workers and Plastic Workers, All Other", text: "Trabajadores de Metal y Plástico, Todos los Otros" },
  { value: "51-5111", label: "Prepress Technicians and Workers", text: "Técnicos y Trabajadores Preimpresión" },
  { value: "51-5112", label: "Printing Press Operators", text: "Operadores de Impresoras" },
  { value: "51-5113", label: "Print Binding and Finishing Workers", text: "Trabajadores de Encuadernación y Acabado de Impresiones" },
  { value: "51-6011", label: "Laundry and Dry-Cleaning Workers", text: "Trabajadores de Lavandería y Limpieza en Seco" },
  { value: "51-6021", label: "Pressers, Textile, Garment, and Related Materials", text: "Prensistas, Textiles, Ropa y Materiales Relacionados" },
  { value: "51-6031", label: "Sewing Machine Operators", text: "Operadores de Máquinas de Sutura" },
  { value: "51-6041", label: "Shoe and Leather Workers and Repairers", text: "Trabajadores y Reparadores de Calzado y Cuero" },
  { value: "51-6042", label: "Shoe Machine Operators and Tenders", text: "Operadores y Ajustadores de Máquinas de Calzado" },
  { value: "51-6051", label: "Sewers, Hand", text: "Sastres a Mano" },
  { value: "51-6052", label: "Tailors, Dressmakers, and Custom Sewers", text: "Sastres, Modistas y Sastres Personalizados" },
  { value: "51-6061", label: "Textile Bleaching and Dyeing Machine Operators and Tenders", text: "Operadores y Ajustadores de Máquinas de Blanqueo y Teñido Textil" },
  { value: "51-6062", label: "Textile Cutting Machine Setters, Operators, and Tenders", text: "Configuradores, Operadores y Ajustadores de Máquinas de Corte Textil" },
  { value: "51-6063", label: "Textile Knitting and Weaving Machine Setters, Operators", text: "Configuradores, Operadores y Ajustadores de Máquinas de Tejido y Entrelazado Textil" },
  { value: "51-6064", label: "Textile Winding, Twisting, and Drawing Out Machine Setters", text: "Configuradores, Operadores y Ajustadores de Máquinas de Enrolado, Torcido y Extracción Textil" },
  { value: "51-9022", label: "Grinding and Polishing Workers, Hand", text: "Trabajadores de Pulido y Lijado a Mano" },
  { value: "51-9023", label: "Mixing and Blending Machine Setters, Operators, and Tenders", text: "Configuradores, Operadores y Ajustadores de Máquinas de Mezcla y Mezclado" },
  { value: "51-9031", label: "Cutters and Trimmers, Hand", text: "Cortadores y Ajustadores a Mano" },
  { value: "51-9032", label: "Cutting and Slicing Machine Setters, Operators, and Tenders", text: "Configuradores, Operadores y Ajustadores de Máquinas de Corte y Slicing" },
  { value: "51-9041", label: "Extruding, Forming, Pressing, and Compacting Machine Setters", text: "Configuradores de Máquinas de Extrusión, Formación, Prensado y Compactación" },
  { value: "51-9051", label: "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders", text: "Operadores y Ajustadores de Horno, Horno Industrial (Kiln), Horno Secador (Oven), Secador (Drier) y Caldero (Kettle)" },
  { value: "51-9061", label: "Inspectors, Testers, Sorters, Samplers, and Weighers", text: "Inspectores, Probadores, Clasificadores, Muestreadores y Pesadores" },
  { value: "51-9081", label: "Dental Laboratory Technicians", text: "Técnicos de Laboratorio Dental" },
  { value: "51-9082", label: "Medical Appliance Technicians", text: "Técnicos de Aplicaciones Médicas" },
  { value: "51-9083", label: "Ophthalmic Laboratory Technicians", text: "Técnicos de Laboratorio Oftalmológico" },
  { value: "51-9111", label: "Packaging and Filling Machine Operators and Tenders", text: "Operadores y Ajustadores de Máquinas de Empaquetado y Llenado" },
  { value: "51-9121", label: "Coating, Painting, and Spraying Machine Setters, Operators", text: "Configuradores, Operadores y Ajustadores de Máquinas de Recubrimiento, Pintura y Rociado" },
  { value: "51-9122", label: "Painters, Transportation Equipment", text: "Pintores de Equipos de Transporte" },
  { value: "51-9123", label: "Painting, Coating, and Decorating Workers", text: "Trabajadores de Pintura, Recubrimiento y Decoración" },
  { value: "51-9141", label: "Semiconductor Processors", text: "Procesadores de Semiconductores" },
  { value: "51-9151", label: "Photographic Process Workers and Processing Machine Operators", text: "Trabajadores de Procesamiento Fotográfico y Operadores de Máquinas de Procesamiento" },
  { value: "51-9191", label: "Adhesive Bonding Machine Operators and Tenders", text: "Operadores y Ajustadores de Máquinas de Unión Adhesiva" },
  { value: "51-9192", label: "Cleaning, Washing, and Metal Pickling Equipment Operators", text: "Operadores de Equipos de Limpieza, Lavado y Picado Metálico" },
  { value: "51-9193", label: "Cooling and Freezing Equipment Operators and Tenders", text: "Operadores y Ajustadores de Equipos de Enfriamiento y Congelamiento" },
  { value: "51-9194", label: "Etchers and Engravers", text: "Grabadores y Talladores" },
  { value: "51-9195", label: "Molders, Shapers, and Casters, Except Metal and Plastic", text: "Moldeadores, Modeladores y Fundidores, Excepto Metal y Plástico" },
  { value: "53-6011", label: "Bridge and Lock Tenders", text: "Ajustadores de Puentes y Cerraduras" },
  { value: "53-6021", label: "Parking Lot Attendants", text: "Asistentes de Estacionamiento" },
  { value: "53-6031", label: "Automotive and Watercraft Service Attendants", text: "Asistentes de Servicio Automotriz y Acuática" },
  { value: "53-6041", label: "Traffic Technicians", text: "Técnicos de Tráfico" },
  { value: "53-6051", label: "Transportation Inspectors", text: "Inspectores de Transporte" },
  { value: "53-7011", label: "Conveyor Operators and Tenders", text: "Operadores y Ajustadores de Transportadores" },
  { value: "53-7021", label: "Crane and Tower Operators", text: "Operadores de Grúas y Torres" },
  { value: "53-7031", label: "Dredge Operators", text: "Operadores de Dragado" },
  { value: "53-7032", label: "Excavating and Loading Machine and Dragline Operators", text: "Operadores de Máquinas de Excavación y Carga y Dragline" },
  { value: "53-7051", label: "Industrial Truck and Tractor Operators", text: "Operadores de Camiones Industriales y Tractores" },
  { value: "53-7061", label: "Cleaners of Vehicles and Equipment", text: "Limpiadores de Vehículos y Equipos" },
  { value: "53-7063", label: "Machine Feeders and Offbearers", text: "Alimentadores y Desalimentadores de Máquinas" },
  { value: "53-7064", label: "Packers and Packagers, Hand", text: "Empacadores y Empaquetadores, a Mano" },
  { value: "53-7072", label: "Pump Operators, Except Wellhead Pumpers", text: "Operadores de Bombas, Excepto Bombas de Pozo" },
  { value: "53-7081", label: "Refuse and Recyclable Material Collectors", text: "Recolectores de Residuos y Materiales Reciclables" },
  { value: "53-7199", label: "Material Moving Workers, All Other", text: "Trabajadores de Movimiento de Materiales, Todos los Otros" },
  { value: "55-1012", label: "Aircraft Launch and Recovery Officers", text: "Oficiales de Lanzamiento y Recuperación de Aeronaves" },
  { value: "55-1013", label: "Armored Assault Vehicle Officers", text: "Oficiales de Vehículos de Asalto Blindados" },
  { value: "55-1014", label: "Artillery and Missile Officers", text: "Oficiales de Artillería y Misiles" },
  { value: "55-1015", label: "Command and Control Center Officers", text: "Oficiales de Centro de Comando y Control" },
  { value: "55-2012", label: "First-Line Supervisors of Weapons Specialists/Crew Members", text: "Supervisores de Primera Línea de Especialistas/ Miembros de Tripulación de Armas" },
  { value: "55-2013", label: "First-Line Supervisors of All Other Tactical Operations Specialists", text: "Supervisores de Primera Línea de Todos los Otros Especialistas en Operaciones Tácticas" },
  { value: "55-3012", label: "Aircraft Launch and Recovery Specialists", text: "Especialistas en Lanzamiento y Recuperación de Aeronaves" },
  { value: "55-3013", label: "Armored Assault Vehicle Crew Members", text: "Miembros del Equipo de Vehículos de Asalto Blindados" },
  { value: "55-3014", label: "Artillery and Missile Crew Members", text: "Miembros del Equipo de Artillería y Misiles" },
  { value: "55-3015", label: "Command and Control Center Specialists", text: "Especialistas de Centro de Comando y Control" },
  { value: "55-3017", label: "Radar and Sonar Technicians", text: "Técnicos de Radar y Sonar" },
  { value: "STUDENT", label: "Student", text: "Estudiante" },
  { value: "RETIRED", label: "Retired", text: "Retirado" },
];