-- Generated by the database client.
CREATE TABLE conduit_transactions(
    id SERIAL NOT NULL,
    transaction_id text NOT NULL,
    quote_id text,
    transaction_type text NOT NULL,
    status text NOT NULL,
    source_id text,
    source_asset text NOT NULL,
    source_network text,
    source_amount numeric(20,8) NOT NULL,
    destination_id text NOT NULL,
    destination_asset text NOT NULL,
    destination_network text,
    destination_amount numeric(20,8) NOT NULL,
    onramp_instructions jsonb,
    documents jsonb,
    purpose text,
    reference text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    conduit_created_at timestamp with time zone,
    raw_response jsonb,
    completed_at timestamp with time zone,
    conduit_id text,
    wallet_address text,
    PRIMARY KEY(id),
    CONSTRAINT conduit_transactions_destination_amount_check CHECK ((destination_amount > (0)::numeric)),
    CONSTRAINT conduit_transactions_source_amount_check CHECK ((source_amount > (0)::numeric)),
    CONSTRAINT conduit_transactions_transaction_type_check CHECK ((transaction_type = ANY (ARRAY['onramp'::text, 'offramp'::text, 'conversion'::text, 'withdrawal'::text, 'deposit'::text])))
);
CREATE UNIQUE INDEX conduit_transactions_transaction_id_key ON public.conduit_transactions USING btree (transaction_id);
CREATE INDEX idx_conduit_transactions_transaction_id ON public.conduit_transactions USING btree (transaction_id);
CREATE INDEX idx_conduit_transactions_quote_id ON public.conduit_transactions USING btree (quote_id);
CREATE INDEX idx_conduit_transactions_type ON public.conduit_transactions USING btree (transaction_type);
CREATE INDEX idx_conduit_transactions_status ON public.conduit_transactions USING btree (status);
CREATE INDEX idx_conduit_transactions_source_id ON public.conduit_transactions USING btree (source_id);
CREATE INDEX idx_conduit_transactions_destination_id ON public.conduit_transactions USING btree (destination_id);
CREATE INDEX idx_conduit_transactions_created_at ON public.conduit_transactions USING btree (created_at DESC);
CREATE INDEX idx_conduit_transactions_status_created ON public.conduit_transactions USING btree (status, created_at DESC);
CREATE INDEX idx_conduit_transactions_wallet_address ON public.conduit_transactions USING btree (wallet_address);
COMMENT ON TABLE conduit_transactions IS 'Stores all transaction records from Conduit Financial (onramp, offramp, conversion, etc.)';
COMMENT ON COLUMN conduit_transactions.transaction_id IS 'Unique transaction identifier from Conduit (e.g., trxn_...)';
COMMENT ON COLUMN conduit_transactions.quote_id IS 'Associated quote identifier (e.g., quote_...)';
COMMENT ON COLUMN conduit_transactions.transaction_type IS 'Type of transaction: onramp, offramp, conversion, withdrawal, deposit';
COMMENT ON COLUMN conduit_transactions.status IS 'Current status of the transaction (e.g., created, pending, completed, failed)';
COMMENT ON COLUMN conduit_transactions.onramp_instructions IS 'Bank transfer instructions for onramp transactions (JSONB)';
COMMENT ON COLUMN conduit_transactions.documents IS 'Array of document IDs for offramp transactions (JSONB)';
COMMENT ON COLUMN conduit_transactions.purpose IS 'Purpose of the transaction (for offramp)';
COMMENT ON COLUMN conduit_transactions.reference IS 'External reference number';
COMMENT ON COLUMN conduit_transactions.raw_response IS 'Complete JSON response from Conduit API for reference';
COMMENT ON COLUMN conduit_transactions.wallet_address IS 'Dirección de la wallet asociada a la transacción';

-- alter table conduit_transactions to when a transactions be deposit and dont have conduit_id extract the conduit id from the wallet_address to
-- see if one of the wallet_addres is the same as the ones in conduit_payment_methods, if it is the same update the conduit_id with the one from conduit_payment_methods
ALTER TABLE conduit_transactions
    ADD CONSTRAINT update_conduit_id
    CHECK (transaction_type = 'deposit' AND conduit_id IS NOT NULL OR transaction_type != 'deposit' OR conduit_id IS NULL)


-- =====================================================
-- Trigger Function to Auto-Update conduit_id for Deposits
-- =====================================================
-- This function automatically updates conduit_id for deposit transactions
-- by matching wallet_address with conduit_payment_methods table

CREATE OR REPLACE FUNCTION update_conduit_id_from_wallet()
RETURNS TRIGGER AS $$
BEGIN
  -- Only process if it's a deposit transaction and conduit_id is NULL
  IF NEW.transaction_type = 'deposit' AND NEW.conduit_id IS NULL AND NEW.wallet_address IS NOT NULL THEN
    
    -- Try to find a matching payment method by wallet_address
    SELECT customer_id INTO NEW.conduit_id
    FROM conduit_payment_methods
    WHERE wallet_address = NEW.wallet_address
      AND type = 'wallet'
      AND status = 'enabled'
    LIMIT 1;
    
    -- Log if we found a match
    IF NEW.conduit_id IS NOT NULL THEN
      RAISE NOTICE 'Auto-updated conduit_id to % for transaction % based on wallet_address %', 
        NEW.conduit_id, NEW.transaction_id, NEW.wallet_address;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- Apply Trigger to conduit_transactions
-- =====================================================

-- Drop trigger if it exists
DROP TRIGGER IF EXISTS trigger_update_conduit_id_from_wallet ON conduit_transactions;

-- Create trigger that fires before INSERT or UPDATE
CREATE TRIGGER trigger_update_conduit_id_from_wallet
  BEFORE INSERT OR UPDATE OF wallet_address, conduit_id, transaction_type
  ON conduit_transactions
  FOR EACH ROW
  EXECUTE FUNCTION update_conduit_id_from_wallet();

-- =====================================================
-- Optional: Backfill existing records
-- =====================================================

-- Update existing deposit transactions that don't have conduit_id
UPDATE conduit_transactions ct
SET conduit_id = cpm.customer_id
FROM conduit_payment_methods cpm
WHERE ct.transaction_type = 'deposit'
  AND ct.conduit_id IS NULL
  AND ct.wallet_address IS NOT NULL
  AND ct.wallet_address = cpm.wallet_address
  AND cpm.type = 'wallet'
  AND cpm.status = 'enabled';

-- =====================================================
-- Verification
-- =====================================================

COMMENT ON FUNCTION update_conduit_id_from_wallet() IS 
  'Automatically updates conduit_id for deposit transactions by matching wallet_address with conduit_payment_methods';

COMMENT ON TRIGGER trigger_update_conduit_id_from_wallet ON conduit_transactions IS 
  'Auto-populates conduit_id for deposits based on wallet_address match in conduit_payment_methods';